### ISSUE TITLE
Link in README doesn't work

### ISSUE THREAD

**Issue by jeroenvanrensen** [yoni206/gen2sat#1]
Hello,

I wanted to inform you that the link in the README file does not work.

When I visit http://www.cs.tau.ac.il/research/yoni.zohar/gen2sat.html, I get a 404 not found error.

**Comment by yoni206** [comment]
Thank you for raising this!
Indeed, the tomcat server I used is not available anymore. I am having trouble building the tool and so publishing a runnable version is postponed.
